# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wSQcoInXgBRsP3rWtgKD8gdJvV7I1FI7
"""

2+2

"""# Python"""